[language-server.typescript-language-server]
command = "npx"
args = ["typescript-language-server", "--stdio"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[language-server.astro-ls]
command = "npx"
args = ["astro-ls", "--stdio"]
