## --- Language Servers ---
 
[language-server.biome]
command = "npx"
args = ["@biomejs/biome", "lsp-proxy"] 

[language-server.astro-ls]
command = "npx"
args = ["astro-ls", "--stdio"]

[language-server.typescript-language-server]
command = "npx"
args = ["typescript-language-server", "--stdio"]


## --- LANGUAGE CONFIGURATIONS ---

[[language]]
name = "javascript"
auto-format = true
language-servers = [
    "typescript-language-server", 
    "biome",
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
    "typescript-language-server",
    "biome",
]

[[language]]
name = "astro"
auto-format = true
language-servers = [
    "astro-ls",
    "biome",
]
